services:
  backend:
    build:
      context: ../..
      dockerfile: infra/docker/backend.Dockerfile
    env_file:
      - ../../.env
    ports:
      - "8081:8080"

  frontend:
    build:
      context: ../..
      dockerfile: infra/docker/frontend.Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
